//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesItem
    {
        public int SalesItemID { get; set; }
        public string BarcodeID { get; set; }
        public int SalesID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
